### ISSUE TITLE
[BUG] /media volume won't map on Unraid

### ISSUE THREAD

**Issue by awhitworth06** [linuxserver/docker-bazarr#111]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I've installed and set this docker up on Unraid, but cannot get it to map my /media folder.

It just says "Bazarr cannot write to this directory." for the "/media" object on the Status page.
![image](https://user-images.githubusercontent.com/37915036/222608872-ece721f6-16ce-4388-953d-1d6a43732bc4.png)

Here are my container mappings:
![image](https://user-images.githubusercontent.com/37915036/222608219-5a4e2717-57cf-4203-82eb-f9bed7a4fc23.png)

Oddly, whenever I go to try and map the folders for Radarr and Sonarr, it always shows a completely different share under the /data directory that I haven't mapped to this container at all. It's showing my /mnt/user/downloads directory for my DelugeVPN container:
![image](https://user-images.githubusercontent.com/37915036/222609021-6de8bc69-8358-458b-ac6d-eabf7b57ece6.png)

This always appears, even if I blank out the /movies and /tv parameters in the container.
I don't know why, because I haven't mapped this share. I mapped my /mnt/user/media share that is used for Plex, Radarr and Sonarr.

I've read through the setup guide, forums, etc., and I cannot find a solution except for mapping the PUID and PGID, which I've done (see container mappings).

### Expected Behavior

 Bazarr should see the mapped /movies and /tv volumes, and shouldn't see the unmapped volumes.

### Steps To Reproduce

1. Install and setup Bazarr on Unraid

### Environment

```markdown
- OS: Unraid 6.11.5
- How docker service was installed: CA App store
```

### CPU architecture

x86-64

### Docker creation

```bash
Installed through CA App store
```

### Container logs

```bash
[migrations] started
[migrations] no migrations found

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
Bazarr: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=XHHRWXT9YB7WE&source=url

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    99
User gid:    100
-------------------------------------

[custom-init] No custom files found, skipping...
2023-03-02 20:23:38,683 - root                             (147dc3598b38) :  INFO (signalr_client:54) - BAZARR trying to connect to Sonarr SignalR feed...
2023-03-02 20:23:38,684 - root                             (147dc3495b38) :  INFO (signalr_client:191) - BAZARR trying to connect to Radarr SignalR feed...
2023-03-02 20:23:38,684 - root                             (147dd1d9fb48) :  INFO (server:67) - BAZARR is started and waiting for request on http://0.0.0.0:6767
2023-03-02 20:23:38,694 - root                             (147dc3392b38) :  INFO (signalr_client:219) - BAZARR SignalR client for Radarr is connected and waiting for events.
[ls.io-init] done.
2023-03-02 20:23:38,723 - root                             (147dc3598b38) :  INFO (signalr_client:74) - BAZARR SignalR client for Sonarr is connected and waiting for events.
```

**Comment by Roxedus** [comment]
You don't have a media mapping to bazarr

**Comment by aptalca** [comment]
> I set /movies to /mnt/user/media/Movies.

That means in Bazarr, when you open `/movies`, you'll be accessing `/mnt/user/media/Movies` on unraid

You're trying to open `/media` inside bazarr, but there is no such folder or mapping

**Comment by awhitworth06** [comment]
That's the problem.

I can't see /movies in Bazarr, even though it is mapped. See my screenshot of the docker mappings above.

It's also telling me it can't access "/media", but I can't find anything saying how to configure that.

**Comment by aptalca** [comment]
I don't see you attempting to access `/movies` in any of the screenshots you posted.

Post your docker run so we know exactly what we're dealing with

**Comment by awhitworth06** [comment]
I'm sorry, but I don't know what that means.

I installed this from the CA App Store in Unraid.

Here is my configuration:
![image](https://user-images.githubusercontent.com/37915036/222780209-ec1cfcdc-2dc3-44a1-b358-68bf559a9352.png)

**Comment by j0nnymoe** [comment]
You've shown us that and it doesn't show a `/media` mapping.

**Comment by aptalca** [comment]
This is not a bug, but pebcak. Let's move the discussion to either discord or discourse: https://www.linuxserver.io/support

**Comment by awhitworth06** [comment]
> 

Where in the documentation can I find how to setup a /media mapping?

**Comment by awhitworth06** [comment]
I fixed the error appearing in the Status by manually adding a container path mapping for "/media" to my Unraid share "/mnt/user/media".

I was then able to manually type "/media/" in my Radarr and Sonarr path mappings and set them.

May be helpful to add this information to the documentation/readme, as it is currently not there.

**Comment by j0nnymoe** [comment]
We provide a basic example of mappings for all our containers. How to add additional mappings to a container is a user's responsibility on reading the documentation for the platform they use on how to do this, be it unraid/Synology/qnap/docker-compose.

There is no need for us to add this to every readme.

**Comment by awhitworth06** [comment]
That's what I'm saying.

The basic mapping requirement of the container path for "/media" isn't in the readme or documentation.

That's why I didn't know I had to map a container path for "/media".

The PUID and PGID parameters are mentioned. So, that's how I knew to add those.

**Comment by aptalca** [comment]
There is no requirement for mapping `/media`. The documentation is accurate. Whatever issue you're facing is a user issue.

Please stop posting in this closed issue and use the proper support channels as linked above. This is your last warning.
