### ISSUE TITLE
[BUG] chown: operation not permitted

### ISSUE THREAD

**Issue by Honken77** [linuxserver/docker-bazarr#112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Starting bazarr with "sudo docker compose up -d" gives me the error:

chown /docker/usenet/configs/bazarr: operation not permitted

Other *arr apps works fine with the same nobody:nogroup NFS share.

### Steps To Reproduce

The same share path works in v1.2.0-ls190 but not v1.2.0-ls191.

I had this same issue with sabnzbd in november, and it was solves here: https://github.com/linuxserver/docker-sabnzbd/issues/154#event-7798596341

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
sudo docker compose up -d

bazarr:
    image: lscr.io/linuxserver/bazarr:v1.2.0-ls190
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - /docker/usenet/configs/bazarr:/config
      - /docker/usenet/library/movies:/movies
      - /docker/usenet/library/tv:/tv
    ports:
      - 6767:6767
    restart: unless-stopped
```

### Container logs

```bash
downgraded versions so I don't have it right now
```

**Comment by thespad** [comment]
This is the only change between those two releases: https://github.com/linuxserver/docker-bazarr/compare/v1.2.0-ls190...v1.2.0-ls191, there haven't been any functional alterations.

**Comment by Honken77** [comment]
Ok. Weird. I couldn't start the containers with 191 because of the error with permissions. I changed to 190 and it started without issue.
Since I had this issue once before with sabnzbd I just assumed it was related, but I never checked the patch notes thoroughly.
