### ISSUE TITLE
TZ quotes handling

### ISSUE THREAD

**Issue by vitalybibikov** [linuxserver/docker-bazarr#113]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Would have expected it to handle TZ as

      - TZ="Europe/Warsaw"
      
      while  only
      
       - TZ=Europe/Warsaw
       
       is supported.
       

### Reason for change

       Not a big deal, but confusing, if config is transfered from sonarr/radarr

**Comment by Roxedus** [comment]
That quoting is wrong in general, as the quotes becomes part of the value. Supported quoting is
```yml
    - "TZ=Europe/Warsaw"
```
or
```yml
   TZ: "Europe/Warsaw"
```
This is not a variable that needs quoting at all, so best bet is to leave them out. The bug would then be that `TZ="Europe/Warsaw"` actually works elsewhere(which would be up to us to fix).

**Comment by aptalca** [comment]
https://docs.linuxserver.io/general/docker-compose#quoting-variables
