### ISSUE TITLE
[FEAT] include subsync

### ISSUE THREAD

**Issue by janusn** [linuxserver/docker-bazarr#115]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I would like to have an option to add [subsync](https://subsync.online/) as a post process.

### Reason for change

subsync is very useful to synchronize the subtitle to the video.

**Comment by Roxedus** [comment]
What makes you belive you need additional software for this feature? AFAIK this is bundled with Bazarr.

**Comment by janusn** [comment]
I am sorry if subsync is already bundled.

The reasons I thought it was not included are:
- subsync is not mentioned in the [Overview page](https://hub.docker.com/r/linuxserver/bazarr).
- subsync cannot be found inside the image.

Could you give me a pointer on how to configure bazarr to add subsync as a postprocess?

Thank you.

**Comment by Roxedus** [comment]
Should be as easy as just enabling it in the bazarr settings.
