### ISSUE TITLE
[BUG] Docker not starting after upgrade

### ISSUE THREAD

**Issue by gilltor** [linuxserver/docker-bazarr#126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Docker is not starting up since I upgraded to latest version of Bazarr using Docker on a Synology NAS.

### Steps To Reproduce

Created a new container from scratch and got the same errors in the log.

### Environment

```markdown
- OS: Synology DSM 7.1
- How docker service was installed: Through the gui of docker.
```

### CPU architecture

x86-64

### Docker creation

```bash
No commands were used.
```

### Container logs

```bash
Bazarr starting...
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/main.py", line 22, in <module>
    from app.check_update import apply_update, check_releases, check_if_new_update  # noqa E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/app/check_update.py", line 15, in <module>
    from .config import settings
  File "/app/bazarr/bin/bazarr/app/config.py", line 8, in <module>
    from subliminal.cache import region
  File "/app/bazarr/bin/bazarr/../libs/subliminal/__init__.py", line 12, in <module>
    from .core import (AsyncProviderPool, ProviderPool, check_video, download_best_subtitles, download_subtitles,
  File "/app/bazarr/bin/bazarr/../libs/subliminal/core.py", line 29, in <module>
    from babelfish import Language, LanguageReverseError
  File "/app/bazarr/bin/bazarr/../libs/babelfish/__init__.py", line 14, in <module>
    from .converters import (LanguageConverter, LanguageReverseConverter, LanguageEquivalenceConverter, CountryConverter,
  File "/app/bazarr/bin/bazarr/../libs/babelfish/converters/__init__.py", line 5, in <module>
    from pkg_resources import iter_entry_points, EntryPoint
ModuleNotFoundError: No module named 'pkg_resources'
Bazarr exited.
```

**Comment by thespad** [comment]
https://info.linuxserver.io/issues/2023-05-22-portainer/

**Comment by gilltor** [comment]
Yeah, I found that in a previous report. 
But didn't quite get it. But after reading it again for a few times, I think I do.

So I shouldn't create/update the containers through the docker GUI but with command line?

**Comment by aptalca** [comment]
We recommend compose, but cli would also work. You just need to recreate with the correct parameters (portainer and syno gui inject incorrect params during update)

**Comment by gilltor** [comment]
Thanks for the info.
You don't happen to have a compose script I can use in the task scheduler?
I think I came across one once when I was looking into docker, but I can't seem to find it again.

Thanks in advance! I'll keep looking tho. :p

**Comment by nomnomnomhb** [comment]
Change the PATH variable to include: **/lsiopy/bin:**
(So for mine: /lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)

**Comment by Oizopower** [comment]
> Change the PATH variable to include: **/lsiopy/bin:** (So for mine: /lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)
> 
> Did wonders for me :).

This works for me as well.

**Comment by thespad** [comment]
This is not a sustainable fix and will just break next time we change anything in the PATH or any other environment variable.

The fundamental issue with the associated tools botching their management of the containers on an update.

**Comment by nomnomnomhb** [comment]
> This is not a sustainable fix and will just break next time we change anything in the PATH or any other environment variable.
> 
> The fundamental issue is with the associated tools botching their management of the containers on an update.

Absolutely, but that's not really a fight which the normal user can hold right (I for instance also do not know what's exactly going on. I see a broken container, I try to fix it)? Just for the sake of fixing it so people can move on, I'd say its proper info.

Thanks for providing though, your efforts are tremendously appreciated.

**Comment by gilltor** [comment]
Well I've made a scheduled task on Synology that I can trigger when I want to update with CLI that stops, removes, updates and creates the container again.
Script is below.

docker stop bazarr
docker rm bazarr
docker pull linuxserver/bazarr
docker run -d --network=bridge -p 6767:6767 -e PUID=xxxx -e PGID=xxx -e TZ=Europe/Brussels --name=bazarr -v /path/to/config:/config -v /path/to/media:/media linuxserver/bazarr

So this issue can be closed. Thanks for nudging me in the correct direction everyone!!! :)

**Comment by gilltor** [comment]
> Fyi, we don't recommend automatic updates and that command you've got in your script, will cause you issues.

It's not an automatic update. It doesn't run scheduled. :) Just for me to trigger it when I need it.
And how will this cause issues?

**Comment by j0nnymoe** [comment]
Well, you've just used our place holder paths and not actually replaced them with your relevant paths. If you want to continue this discussion, jump over to our discord or forum.

**Comment by gilltor** [comment]
Oh, those paths aren't the ones I'm using. Just as an example. I tested the script and it works. :)
