### ISSUE TITLE
[FEAT] Add missing repo/site https://www.easternspirit.org/forum/index.php?/files/

### ISSUE THREAD

**Issue by Arkadietz** [linuxserver/docker-bazarr#140]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Hello,

Could you please add the following repo/site (https://www.easternspirit.org/forum/index.php?/files/) for subs? 

Thank you in advance.

### Reason for change

Because this is a great repo for all chinese, korean and so on films.

**Comment by j0nnymoe** [comment]
Report to bazaar, not use.
