### ISSUE TITLE
[BUG]  ModuleNotFoundError: No module named 'distutils' #2740 

### ISSUE THREAD

**Issue by punteroanull** [linuxserver/docker-bazarr#145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It doesn't work at all.

File "/app/bazarr/bin/bazarr/app/get_args.py", line 6, in
from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils'
Traceback (most recent call last):
File "/app/bazarr/bin/bazarr.py", line 10, in

build_version | Linuxserver.io version:- v1.1.4-ls180
Build-date:- 2023-02-02T14:28:57-06:00

### Steps To Reproduce

Just run the container.

### Environment

```markdown
build_version | Linuxserver.io version:- v1.1.4-ls180
Build-date:- 2023-02-02T14:28:57-06:00

- How docker service was installed: portainer
```

### CPU architecture

x86-64

### Docker creation

```bash
portainer
```

### Container logs

```bash
File "/app/bazarr/bin/bazarr/app/get_args.py", line 6, in
from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils'
Traceback (most recent call last):
File "/app/bazarr/bin/bazarr.py", line 10, in
```

**Comment by j0nnymoe** [comment]
https://info.linuxserver.io/issues/2023-05-22-portainer/

**Comment by Roxedus** [comment]
You did infact *not* search the existing issues. https://github.com/linuxserver/docker-bazarr/issues/143#issuecomment-2426703802
