### ISSUE TITLE
[FEAT] Include paho-mqtt to enable Apprise mqtt:// support

### ISSUE THREAD

**Issue by brycied00d** [linuxserver/docker-bazarr#146]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I would like for the `paho-mqtt` Python module to be included in this image.

### Reason for change

It would be helpful to me if Bazarr's Apprise feature would support `mqtt://`  URIs.  The `linuxserver/docker-sabnzbd` image already supports this (https://github.com/linuxserver/docker-sabnzbd/blame/4.3.0-ls160/package_versions.txt#L80)

At present, attempting to configure a notification in Bazarr that uses "Apprise API" with an "mqtt://" URI results in an error:
```
2024-11-22 13:50:09,830 - apprise                          (790b3cc1cb30) :  ERROR (Apprise:173) - mqtt:// is disabled on this system.
2024-11-22 13:50:09,830 - apprise                          (790b3cc1cb30) :  ERROR (Apprise:456) - There are no service(s) to notify
```
That error is the result of bazarr attempting and failing to import the `paho-mqtt` module (https://github.com/morpheus65535/bazarr/blob/v1.4.5/libs/apprise/plugins/NotifyMQTT.py#L48-L56)

### Proposed code change

I'm not too familiar with LSio's image building system so I'm afraid I don't know how to add this. It appears that with `linuxserver/docker-sabnzbd`, it was automatically pulled in by sabnzbd's own `requirements.txt` with their introduction of the Apprise integration (https://github.com/sabnzbd/sabnzbd/pull/2796).  Does this issue needs to be taken upstream to bazarr for them to update their `requirements.txt`?

**Comment by brycied00d** [comment]
Bumping to express my continued interest.

**Comment by aptalca** [comment]
You can use the universal package install mod to install it

**Comment by brycied00d** [comment]
@aptalca Oh that's perfect, thank you!  Sorry for the noise.
