### ISSUE TITLE
Private Container Error

### ISSUE THREAD

**Issue by gbailey4** [linuxserver/docker-bazarr#3]
I'm not able to pull this via docker, here's the error I receive:
```
Error response from daemon: pull access denied for linuxserver/bazarr, repository does not exist or may require 'docker login'
```

**Comment by CHBMB** [comment]
That's because we haven't released it yet.....

So the repository doesn't exist.

**Comment by gbailey4** [comment]
Thanks! Is there an ETA on release?

**Comment by CHBMB** [comment]
Soonish....
