### ISSUE TITLE
bazarr docker using all available memory (47.84GB)

### ISSUE THREAD

**Issue by carv-it-up** [linuxserver/docker-bazarr#33]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
Not have any reason to use this much memory

## Current Behavior
CONTAINER ID        NAME                    CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
79de0faf2b65        bazarr-4K               0.04%               100.8MiB / 125.9GiB   0.08%               1.85MB / 7.84kB     15.8GB / 209kB      25
28f29620ba34        bazarr                  0.04%               **47.84GiB** / 125.9GiB   37.98%              10.1MB / 323kB      12.8GB / 209kB      27

## Steps to Reproduce
Unable to reproduce yet. System did this last night and locked up then again while I was at work this afternoon. Setting -m to 8 gigs and seeing if I will be able to get more information the next time it occurs.

Mainly posting incase anyone else is also investigating the issue.

## Environment
**OS:**      UnRaid Docker
**CPU architecture:** x86_64/arm32/arm64      AMD64 (dual xeon e5 2697v2)
**How docker service was installed:**      UnRaid Community Apps
Bazarr Version:0.8.3.4
Sonarr Version:2.0.0.5338
Radarr Version:0.2.0.1450
Operating System:Linux-4.19.56-Unraid-x86_64-with
Python Version:2.7.16

For now just adding -m 8g to limit usage and prevent docker from being overloaded.

## Command used to create docker container (run/create/compose/screenshot)
docker run -d --name='bazarr' --net='br0' --ip='192.168.17.238' -e TZ="America/Los_Angeles" -e HOST_OS="Unraid" -e 'TCP_PORT_6767'='6767' -e 'PUID'='99' -e 'PGID'='100' -v '/mnt/disks/ALLSPARK_GARGANTUAN/Media/Movies/':'/movies':'rw,slave' -v '/mnt/disks/ALLSPARK_GARGANTUAN/Media/TV Shows/':'/tv':'rw,slave' -v '/mnt/user/appdata/bazarr':'/config':'rw' -m 8g 'linuxserver/bazarr' 
1d262dae6d4c181787a29f1cb5e615a62761fc530b8cdf1c5608efa3be467d4f

## Docker logs
System locked both times unable to provide

**Comment by carv-it-up** [comment]
Issue has not recurred. Closing ticket.

**Comment by symetryczny** [comment]
Hi, I have the exact problem in unRAID where bazarr docker is consuming all available RAM. I managed to isolate the problem to the python running within the container being responsible for high memory usage
