### ISSUE TITLE
bazarr container using all available RAM memory

### ISSUE THREAD

**Issue by symetryczny** [linuxserver/docker-bazarr#37]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior

Bazarr container should not consume all available RAM memory
## Current Behavior

Bazarr container using all available host RAM memory thus crashing the host system and making it unstable
## Steps to Reproduce

Once the bazar container is started via GUI, within hours of starting it consumes all available RAM memory

The problem started on unRAID 6.7.2 back in December 2019. I was going through the exercise of encrypting my data array. I would move all the data from one of the disks to another disk, stop the array, reformat the disk as encrypted and add it back to the array using the "New config" function.
After a few disks were done I observed that my unRAID system would become unstable and all RAM memory consumed. Whilst troubleshooting I was able to pinpoint docker service being responsible and in "top" program I could see python consuming gigabytes (100+ G) of RAM. Once I killed python the system would become stable again and all the incorrectly allocated RAM available again.
In order to troubleshoot and see which of the containers is causing the problem I added "--memory=10g --oom-kill-disable" parameters. When started the container consumes ~150M and then after a few hours spikes to the available maximum within minutes.
I updated unRAID to 6.8.0 and then 6.8.1. but it did not resolve the problem.
The same behaviour was reported in issue #33 

## Environment
**OS:**      unRAID 6.8.1
**CPU architecture:** x86_64      
**How docker service was installed:**      unRAID's Communicty Applications plugin

## Command used to create docker container (run/create/compose/screenshot)

root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker create --name='bazarr' --net='bridge' --cpuset-cpus='2,3,4,14,15,16' -e TZ="Europe/Berlin" -e HOST_OS="Unraid" -e 'PUID'='99' -e 'PGID'='100' -p '6767:6767/tcp' -v '/mnt/user/filmy/':'/movies':'rw' -v '/mnt/user/seriale/':'/tv':'rw' -v '/mnt/user/appdata/bazarr':'/config':'rw' --memory=10g --oom-kill-disable 'linuxserver/bazarr'

## Docker logs

To be provided, waiting for the docker to crash again.

**Comment by aptalca** [comment]
Likely a bazarr issue (mem leak)

Try to get the logs (both docker and bazarr)

**Comment by symetryczny** [comment]
Sorry for the delay. I reinstalled the new container version and the problem is gone, I mark it as closed.
