### ISSUE TITLE
reverse proxy port

### ISSUE THREAD

**Issue by yangtfu** [linuxserver/docker-bazarr#38]
I use a nginx reversie proxy to bazarr web ui, because my isp blocked 80 and 443 port, I used another port to access bazarr, the https://my.domain:port/bazarr request will redirect to https://my.domain/bazarr, do you have a solution for this?

**Comment by aptalca** [comment]
That's not a docker related bug or issue, so closing this.

You can contact bazarr or your reverse proxy solution.
