### ISSUE TITLE
Synology Docker - Bazarr stops working after initial setup wizard

### ISSUE THREAD

**Issue by mikedorsi** [linuxserver/docker-bazarr#47]
Bazarr asks to restart once the initial wizard setup is finished.  When it goes to restart it never comes back up.

Synology DS1019+ running DSM 6.2.3-25426

Container Information:
PGID - 101
PUID - 1026
TZ - America/Los_Angeles
Port - 6767
UMASK_SET - 022 (Tried with and without since it's optional)
Enable Auto-Restart
Execute container using higher privileges (Tried with and without this setting toggled)

Volumes:
/docker/Bazarr/config
/Archive/Video/TV Shows
/Storage/Video/Movies
/Storage/Video/Kids
/Storage/Video/Stand Up

Docker Logs:
```
Bazarr starting...
2020-06-25 02:44:47,484 - root
(7fc08fa91d48) :  INFO (main:2263) - BAZARR is started and waiting for request on http://192.168.1.116:6767/bazarr/
Traceback (most recent call last):
File "/app/bazarr/bazarr/main.py", line 2265, in <module>
server.start()                                                                                  
File "/app/bazarr/bazarr/../libs/cherrypy/wsgiserver/__init__.py", line 2008, in start
raise socket.error(msg)
OSError: No socket could be created -- (('192.168.1.116', 6767): [Errno 99] Address not available)
Traceback (most recent call last):
File "/app/bazarr/bazarr.py", line 86, in <module>
os.wait()
ChildProcessError: [Errno 10] No child process
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
File "/app/bazarr/bazarr.py", line 37, in <lambda>
atexit.register(lambda: ep.kill())
File "/usr/lib/python3.8/subprocess.py", line 1941, in kill
self.send_signal(signal.SIGKILL)
File "/usr/lib/python3.8/subprocess.py", line 1931, in send_signal
os.kill(self.pid, sig)
ProcessLookupError: [Errno 3] No such process
```

Bazarr Log:
```
|BAZARR is started and waiting for request on http://192.***.***.***:6767/bazarr/|
```

**Comment by j0nnymoe** [comment]
Try restarting the container instead of the application within the container.

**Comment by mikedorsi** [comment]
@j0nnymoe That's what I have been doing.  Sorry that I didn't provide that detail clearly.

**Comment by mikedorsi** [comment]
I have resolved the issue.  I apologize.  Please close/remove this ticket.
