### ISSUE TITLE
Docker rate limits reached and possible workaround

### ISSUE THREAD

**Issue by pwsh** [linuxserver/docker-bazarr#48]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

The issue is new to docker due to rate limits being introduced. Open source projects can apply for an exemption from the rate limits.

Rate limit information: https://www.docker.com/increase-rate-limits
FAQ: https://www.docker.com/pricing/resource-consumption-updates
Blog post on open source: https://www.docker.com/blog/expanded-support-for-open-source-software-projects/
Open Source Project Application: https://www.docker.com/community/open-source/application

------------------------------

## Expected Behavior
Pulling docker images via anonymous request should work without rate limiting

## Current Behavior
Tuesday 15 December 2020  14:32:32 -0600 (0:00:00.052)       0:00:10.400 ******
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Error pulling image linuxserver/bazarr:latest - 500 Server Error: Internal Server Error (\"toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit\")"}
        to retry, use: --limit @/opt/communityapps/apps/bazarr.retry

## Steps to Reproduce
More than 100 docker pull requests need to be performed unauthenticated in a 6 hour period by a single IP

## Environment
N/A

## Command used to create docker container (run/create/compose/screenshot)
N/A

## Docker logs
N/A

**Comment by j0nnymoe** [comment]
Use the ghcr.io image links that are in our readme's.

**Comment by aptalca** [comment]
you can pull the same images from the github container registry by prepending the image name with `ghcr.io/` so instead of `linuxserver/radarr`, use `ghcr.io/linuxserver/radarr`

In fact all of our readmes now reference that new endpoint due to docker hub limits

**Comment by pwsh** [comment]
Thank you! I'll reach out to the https://github.com/PGBlitz team as this is where it is being referenced.
