### ISSUE TITLE
Bazarr suddenly stopped working. Dogpile.cache error

### ISSUE THREAD

**Issue by Lestat680** [linuxserver/docker-bazarr#53]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Program should start
## Current Behavior

It keeps rebooting the program before it starts. 
 
## Environment
**OS:** Libreelec 9.2.6
**CPU architecture:** x86_64
**How docker service was installed:**

Official docker repo. 
## Command used to create docker container (run/create/compose/screenshot)

![Screenshot_20210203_171839_com android chrome](https://user-images.githubusercontent.com/78495815/106778798-a3fddf80-6646-11eb-86fc-69c012c26e32.jpg)
Was created almost a year ago. Through commands. Cannot remember the code. 
But it worked for a long time. Suddenly stopped working. Recreating with new poll in portainer does not work. 
## Docker logs

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.

[s6-init] ensuring user provided files have correct perms...exited 0.

[fix-attrs.d] applying ownership & permissions fixes...

[fix-attrs.d] done.

[cont-init.d] executing container initialization scripts...

[cont-init.d] 01-envfile: executing... 

[cont-init.d] 01-envfile: exited 0.

[cont-init.d] 10-adduser: executing... 

usermod: no changes

-------------------------------------

          _         ()

         | |  ___   _    __

         | | / __| | |  /  \ 

         | | \__ \ | | | () |

         |_| |___/ |_|  \__/

Brought to you by linuxserver.io

-------------------------------------

To support the app dev(s) visit:

Bazarr: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=XHHRWXT9YB7WE&source=url

To support LSIO projects visit:

https://www.linuxserver.io/donate/

-------------------------------------

GID/UID

-------------------------------------

User uid:    65534

User gid:    65534

-------------------------------------

[cont-init.d] 10-adduser: exited 0.

[cont-init.d] 30-config: executing... 

[cont-init.d] 30-config: exited 0.

[cont-init.d] 99-custom-files: executing... 

[custom-init] no custom files found exiting...

[cont-init.d] 99-custom-files: exited 0.

[cont-init.d] done.

[services.d] starting services

[services.d] done.

Bazarr starting...

Traceback (most recent call last):

  File "/app/bazarr/bazarr/main.py", line 19, in <module>

    from logger import empty_log

  File "/app/bazarr/bazarr/logger.py", line 11, in <module>

    from config import settings

  File "/app/bazarr/bazarr/config.py", line 5, in <module>

    from subliminal.cache import region

  File "/app/bazarr/bazarr/../libs/subliminal/__init__.py", line 14, in <module>

    from .cache import region

  File "/app/bazarr/bazarr/../libs/subliminal/cache.py", line 5, in <module>

    from dogpile.cache import make_region

ModuleNotFoundError: No module named 'dogpile.cache'

Bazarr exited.

**Comment by thelamer** [comment]
We install all of the requirements for this project upstream. I suspect this issue was temporary. 

https://github.com/linuxserver/docker-bazarr/blob/master/Dockerfile#L52-L53
