### ISSUE TITLE
Cannot start bazarr on docker after upgrade to v0.9.1

### ISSUE THREAD

**Issue by eevlogiev** [linuxserver/docker-bazarr#54]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Normal process startup listening on port 6767.

## Current Behavior
I am trying to start the Docker container once I pulled the latest bazarr docker image from linuxserver.io. Process is failing with the following error:
```
Current thread 0x75f79390 (most recent call first):                                                                                                                               
<no Python frame>                                                                                                                                                                 
Fatal Python error: pyinit_main: can't initialize time                                                                                                                            
Python runtime state: core initialized                                                                                                                                            
PermissionError: [Errno 1] Operation not permitted   
```

## Steps to Reproduce
On NAS QNAP TS-231P2, Pull latest Docker image from linuxserver.io - version 0.9.1 and try to start it.

## Environment
**OS:**
**CPU architecture:** arm32
**How docker service was installed:**
via Container Station from Docker Hub using latest linuxserver.io image.
Bazarr: v 0.9.1
Docker 20.10.3 on linux, arm
QNAP TS-231P2
OS: Arm 32bit

## Command used to create docker container (run/create/compose/screenshot)
<img width="802" alt="Screenshot 2021-02-22 at 4 07 48" src="https://user-images.githubusercontent.com/27862102/108648955-11be5e00-74c5-11eb-819d-894c7cbd77c2.png">

**Comment by Roxedus** [comment]
Your log probably mentions this link: https://docs.linuxserver.io/faq#libseccomp

**Comment by eevlogiev** [comment]
@Roxedus ,
thanks for sharing that but QNAP is using some proprietary Linux base and I these Debian packages cannot be installed on it:
```
[~] # dpkg -i libseccomp2_2.4.4-1~bpo10+1_armhf.deb
-sh: dpkg: command not found 
```

Any other workaround here?

**Comment by j0nnymoe** [comment]
@eevlogiev you would need to ask QNAP about getting this package updated due to the nature of the OS.

**Comment by eevlogiev** [comment]
The issue was fixed after upgrading QNAP Container Station to latest version 2.3.4.1698.

Thanks.
