### ISSUE TITLE
Bazarr is moving to a release only deployment strategy

### ISSUE THREAD

**Issue by morpheus65535** [linuxserver/docker-bazarr#56]
Hey mates,

Currently, the development tag is built from sources. As we are moving the UI to React, we're gonna have to run build in pipeline and include the result in releases archives. For matser branch, we'll use releases but for every push to development branch, we create a pre-release. Would it be possible to switch the development tag to those pre-releases?

This could be done right now as we already produce those pre-releases.

Thanks!

**Comment by aptalca** [comment]
Thanks for the heads up. We can absolutely switch to pulling the dev builds from GitHub pre-releases. The only thing to add is, by default, our dev branch will build both stable and pre-releases and the stable will build only stable. Is that ok? If not, we can change it so dev only builds pre-releases.

**Comment by morpheus65535** [comment]
That's perfectly fine, no need to change this default behavior. Releases are basically a "copy" of the last pre-release with an update semver version. Thanks!

**Comment by aptalca** [comment]
Done in #57

**Comment by morpheus65535** [comment]
Thanks!
