### ISSUE TITLE
package_info file

### ISSUE THREAD

**Issue by morpheus65535** [linuxserver/docker-bazarr#58]
It would be helpful to know what branch we are currently using inside a container. I understand that's the kind of information you can provide trough `package_info` file. Would it be possible to implement this for Bazarr please? Thanks!

**Comment by aptalca** [comment]
Sure, did you want it to be in the same format as some of the other ones like this?
https://github.com/linuxserver/docker-sonarr/blob/master/Dockerfile#L32

**Comment by morpheus65535** [comment]
Yes it's gonna be perfectly fine. Thanks!

**Comment by Roxedus** [comment]
Is the code to read this in the latest pre-release? Testing the PR we have.

**Comment by morpheus65535** [comment]
No not yet. I will add it to dev branch today.

**Comment by Roxedus** [comment]
Cool, does the changes in #59 look good? Or do you want to wait until the code is in, so we can test before merge?

**Comment by morpheus65535** [comment]
Looks good to me. You can merge it. Don't forget to change the branch value for latest tag ;-)

Thanks!

**Comment by aptalca** [comment]
@morpheus65535 
Development tag is merged and pushed. We can use that for the test once you make the changes upstream. If they look good, we'll push the changes to latest.

**Comment by morpheus65535** [comment]
Would it be possible to have the `package_info` file one level up in directories tree? 

For Sonarr and Radarr, this file is in `/app/bin` where you can also find a sonarr/radarr directory. For Bazarr, it's in `/app/bazarr` directly. If you prefer to move `bazarr` directory in `/app/bin` and leave the `package_info` file in place, it's fine for me also.

Thanks!

**Comment by aptalca** [comment]
@morpheus65535 does #60 look good? It matches the other *arrs now

**Comment by morpheus65535** [comment]
@aptalca looks good to me! Thanks!

**Comment by aptalca** [comment]
new development build pushed. I'll PR the same changes to master/latest as well
