### ISSUE TITLE
Bazarr release pipeline now create bazarr.zip asset

### ISSUE THREAD

**Issue by morpheus65535** [linuxserver/docker-bazarr#62]
From now on, for both dev and master branch, we create a bazarr.zip file on each release/pre-release. It can be downloaded using the following URL (for example): https://github.com/morpheus65535/bazarr/releases/download/v0.9.4/bazarr.zip

Could you update all your images to use it?

Starting with 0.9.5 final, you wont get the required files for Bazarr to start from tarball. 

Thanks!

**Comment by aptalca** [comment]
Will do. Thanks for the heads up.

**Comment by morpheus65535** [comment]
Always a pleasure! Thanks for providing those images :-)
