### ISSUE TITLE
Bazarr WebUI no longer works

### ISSUE THREAD

**Issue by Rhfelwr** [linuxserver/docker-bazarr#66]
Installed on Portainer with Docker

I get this log:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
Bazarr: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=XHHRWXT9YB7WE&source=url

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/main.py", line 40, in <module>
    from server import app, webserver
  File "/app/bazarr/bin/bazarr/server.py", line 83, in <module>
    webserver = Server()
  File "/app/bazarr/bin/bazarr/server.py", line 33, in __init__
    self.server = create_server(app,
  File "/app/bazarr/bin/bazarr/../libs/waitress/server.py", line 81, in create_server
    last_serv = TcpWSGIServer(
  File "/app/bazarr/bin/bazarr/../libs/waitress/server.py", line 239, in __init__
    self.bind_server_socket()
  File "/app/bazarr/bin/bazarr/../libs/waitress/server.py", line 368, in bind_server_socket
    self.bind(sockaddr)
  File "/app/bazarr/bin/bazarr/../libs/waitress/wasyncore.py", line 398, in bind
    return self.socket.bind(addr)
OSError: [Errno 99] Address not available
Bazarr starting...
Bazarr exited.
```

Things I tried:
- assigning a different port instead of the original 6767
- assigning a random port

**Comment by sarvesh-lad** [comment]
Same here, just hangs there on docker:

```
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
Bazarr: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=XHHRWXT9YB7WE&source=url

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2021-04-20 21:28:03,054 - root                             (7f81aa1beb48) :  INFO (server:40) - BAZARR is started and waiting for request on http://0.0.0.0:6767
```


the contianer log just shows this:


```
20/04/2021 21:25:16|INFO    |root                            |BAZARR is started and waiting for request on http://0.***.***.***:6767|
20/04/2021 21:28:03|INFO    |root                            |BAZARR is started and waiting for request on http://0.***.***.***:6767|
```

**Comment by aptalca** [comment]
Those are not the same and neither of you filled out the issue template

**Comment by sarvesh-lad** [comment]
My bad, I fixed it, looks like the reverse proxy path got blanked out and had to re-enter it.

**Comment by morpheus65535** [comment]
> Installed on Portainer with Docker
> 
> I get this log:
> 
> ```
> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> [s6-init] ensuring user provided files have correct perms...exited 0.
> [fix-attrs.d] applying ownership & permissions fixes...
> [fix-attrs.d] done.
> [cont-init.d] executing container initialization scripts...
> [cont-init.d] 01-envfile: executing...
> [cont-init.d] 01-envfile: exited 0.
> [cont-init.d] 10-adduser: executing...
> 
> -------------------------------------
>           _         ()
>          | |  ___   _    __
>          | | / __| | |  /  \
>          | | \__ \ | | | () |
>          |_| |___/ |_|  \__/
> 
> 
> Brought to you by linuxserver.io
> -------------------------------------
> 
> To support the app dev(s) visit:
> Bazarr: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=XHHRWXT9YB7WE&source=url
> 
> To support LSIO projects visit:
> https://www.linuxserver.io/donate/
> -------------------------------------
> GID/UID
> -------------------------------------
> 
> User uid:    1000
> User gid:    1000
> -------------------------------------
> 
> [cont-init.d] 10-adduser: exited 0.
> [cont-init.d] 30-config: executing...
> [cont-init.d] 30-config: exited 0.
> [cont-init.d] 99-custom-files: executing...
> [custom-init] no custom files found exiting...
> [cont-init.d] 99-custom-files: exited 0.
> [cont-init.d] done.
> [services.d] starting services
> [services.d] done.
> Traceback (most recent call last):
>   File "/app/bazarr/bin/bazarr/main.py", line 40, in <module>
>     from server import app, webserver
>   File "/app/bazarr/bin/bazarr/server.py", line 83, in <module>
>     webserver = Server()
>   File "/app/bazarr/bin/bazarr/server.py", line 33, in __init__
>     self.server = create_server(app,
>   File "/app/bazarr/bin/bazarr/../libs/waitress/server.py", line 81, in create_server
>     last_serv = TcpWSGIServer(
>   File "/app/bazarr/bin/bazarr/../libs/waitress/server.py", line 239, in __init__
>     self.bind_server_socket()
>   File "/app/bazarr/bin/bazarr/../libs/waitress/server.py", line 368, in bind_server_socket
>     self.bind(sockaddr)
>   File "/app/bazarr/bin/bazarr/../libs/waitress/wasyncore.py", line 398, in bind
>     return self.socket.bind(addr)
> OSError: [Errno 99] Address not available
> Bazarr starting...
> Bazarr exited.
> ```
> 
> Things I tried:
> 
> * assigning a different port instead of the original 6767
> * assigning a random port

You specified a listening address in Bazarr general config that isn't available inside the container (ie: you can't bind to the host address from inside a container in bridge mode). You should leave it as `0.0.0.0`. You can fix this by editing Bazarr config.ini file and make sure `[general]-->ip=0.0.0.0` then restart Bazarr container.
