### ISSUE TITLE
Connection refused from all the providers (urllib3.connectionpool)

### ISSUE THREAD

**Issue by Manuel5cc** [linuxserver/docker-bazarr#70]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Bazarr should connect to the providers to search for the subtitles

## Current Behavior

All the providers are throwing connection errors from a week ago.

## Steps to Reproduce

1. Open Bazarr
2. Search for subtitles (manually or scheduled)

## Environment
**OS:** Raspbian GNU/Linux 10 (buster) / Docker
**CPU architecture:** arm32 (raspberry Pi 4)
**How docker service was installed:** From official docker hub via Portainer

## Command used to create docker container (run/create/compose/screenshot)

Installed from Portainer UI

## Docker logs

[_bazarr_logs (1).txt](https://github.com/linuxserver/docker-bazarr/files/6489114/_bazarr_logs.1.txt)
[docker.log](https://github.com/linuxserver/docker-bazarr/files/6489116/docker.log)

**Comment by tobbenb** [comment]
Please supply all info we ask for and also full docker log.

**Comment by Manuel5cc** [comment]
Updated with missing details. If anything important is missing please let me know.

**Comment by Roxedus** [comment]
With full docker log, saarg meant the whole log for the container, including the banner.

**Comment by Manuel5cc** [comment]
> With full docker log, saarg meant the whole log for the container, including the banner.

With "banner" did you mean this part?:

```
Bazarr starting...

Bazarr exited.

[cont-finish.d] executing container finish scripts...

[cont-finish.d] done.

[s6-finish] waiting for services.

[s6-finish] sending all processes the TERM signal.

[s6-finish] sending all processes the KILL signal and exiting.

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.

[s6-init] ensuring user provided files have correct perms...exited 0.

[fix-attrs.d] applying ownership & permissions fixes...

[fix-attrs.d] done.

[cont-init.d] executing container initialization scripts...

[cont-init.d] 01-envfile: executing... 

[cont-init.d] 01-envfile: exited 0.

[cont-init.d] 10-adduser: executing... 

usermod: no changes


-------------------------------------

          _         ()

         | |  ___   _    __

         | | / __| | |  /  \ 

         | | \__ \ | | | () |

         |_| |___/ |_|  \__/



Brought to you by linuxserver.io

-------------------------------------


To support the app dev(s) visit:

Bazarr: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=XHHRWXT9YB7WE&source=url


To support LSIO projects visit:

https://www.linuxserver.io/donate/

-------------------------------------

GID/UID

-------------------------------------


User uid:    0

User gid:    0

-------------------------------------


[cont-init.d] 10-adduser: exited 0.

[cont-init.d] 30-config: executing... 

[cont-init.d] 30-config: exited 0.

[cont-init.d] 99-custom-files: executing... 

[custom-init] no custom files found exiting...

[cont-init.d] 99-custom-files: exited 0.

[cont-init.d] done.

[services.d] starting services

[services.d] done.

```

It was in the updated log file.

**Comment by Roxedus** [comment]
This look like a app issue. Also note that we dont support running the applications as root.

**Comment by Manuel5cc** [comment]
> This look like a app issue. Also note that we dont support running the applications as root.

I have changed the permissions to a non-root user but doesn't impact the error status.
Also... What does it mean if it's an app issue? I'm using the image "as is" so... Should I expect a fix in future releases?

**Comment by Roxedus** [comment]
It means the issue isn't with the container, but with bazarr. This issuetracker is for the image

**Comment by morpheus65535** [comment]
@Manuel5cc disable bsplayer provider. It's broken.

**Comment by Manuel5cc** [comment]
> @Manuel5cc disable bsplayer provider. It's broken.

Well this actually worked! I guess the error on one provider was preventing to jump to the next.

**Comment by morpheus65535** [comment]
> > @Manuel5cc disable bsplayer provider. It's broken.
> 
> Well this actually worked! I guess the error on one provider was preventing to jump to the next.

There's improvements for this provider in beta but it's far from perfect. This provider is working hard to keep us out.
