### ISSUE TITLE
New python module required: cryptography

### ISSUE THREAD

**Issue by morpheus65535** [linuxserver/docker-bazarr#71]
Can you add this module to both dev and master images please?

https://pypi.org/project/cryptography/

Thanks!

**Comment by aptalca** [comment]
Sure, but do you mean it will be included in bazarr's requirements.txt or did you want us to add it manually?

**Comment by morpheus65535** [comment]
I will add it to Bazarr requirements.txt but I was under the impression you were not using requirements.txt during build process. I've just check your Dockerfile and you are using it so I guess there's nothing to do here ;-)

Thanks and sorry to have disturbed you on a Sunday. Have a nice day!

**Comment by aptalca** [comment]
@morpheus65535 no worries, I think it's hotio who doesn't use the requirements file.

But, I'm glad you told us because even though we use the requirements file, some of the packages have os dependencies (cryptography is one of them).

We'll make sure they are all added.

Thanks

**Comment by morpheus65535** [comment]
Thank you very much! I'll reopen this issue then as a reminder.

**Comment by Roxedus** [comment]
#72 and #73 sets us up to handle this.

**Comment by morpheus65535** [comment]
@Roxedus so once those PR have been fixed and merged, I'm gonna be ready to go with the new requirements.txt? Thanks btw!

**Comment by aptalca** [comment]
Both PRs merged, built and pushed. All ready to go. And thank so much for the heads up.

**Comment by morpheus65535** [comment]
> Both PRs merged, built and pushed. All ready to go. And thanks so much for the heads up.

Thanks guys! Always a pleasure to work with you!
