### ISSUE TITLE
Bazarr keep hangs on Sonarr connection

### ISSUE THREAD

**Issue by luizbird** [linuxserver/docker-bazarr#74]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Bazarr should connect to Sonarr to pull TV list

## Current Behavior
For some reason, Bazarr keep getting erro on connect to Sonarr. The log files gets really huge with the same message:

04/08/2021 13:51:17|INFO    |root                            |BAZARR SignalR client for Sonarr is now disconnected.|
04/08/2021 13:51:17|ERROR   |root                            |BAZARR cannot parse JSON returned by SignalR feed. This is a known issue when Sonarr doesn't have write permission to it's /config/xdg directory.|

I tryied to "reset permission" on all folders but no success.

## Steps to Reproduce
1. Just connect to Sonarr with the API Key. It hangs when click on Save and the log file starts to be filled with the same error message mentioned above.

## Environment
**OS:** OpenMedia Vault v5.6.13-1 (Usul)
**CPU architecture:** x86_64
**How docker service was installed:** Via Portainer

## Command used to create docker container (run/create/compose/screenshot)
Portainer

## Docker logs
04/08/2021 13:51:17|INFO    |root                            |BAZARR SignalR client for Sonarr is now disconnected.|
04/08/2021 13:51:17|ERROR   |root                            |BAZARR cannot parse JSON returned by SignalR feed. This is a known issue when Sonarr doesn't have write permission to it's /config/xdg directory.|-->

**Comment by Roxedus** [comment]
This doesnt sound as a bazarr issue, also not a container issue.
