### ISSUE TITLE
Bazarr fails to sync episodes from sonarr, stacktrace bellow

### ISSUE THREAD

**Issue by TiboGabriels** [linuxserver/docker-bazarr#75]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

bazar syncs episodes from sonarr and they appear in the UI.

## Steps to Reproduce

1.Add Sonarr in settings
2. man/auto update series list from sonarr
3. man/auto sync episodes from sonarr
4. get error: *Job "Sync episodes with Sonarr (trigger: interval[1:00:00], next run at: 2021-08-06 10:38:07 CEST)" raised an exception*

## Environment
**OS:** OpenMediaVault 5.6.13.1 (Usul) - Linux 5.4.119-1-pve kernel
**CPU architecture:** **x86_64**/arm32/arm64
**How docker service was installed:**

In Portainer using a stack (like docker compose)

## Command used to create docker container (run/create/compose/screenshot)

```
bazarr:
   image: ghcr.io/linuxserver/bazarr
   container_name: bazarr
   network_mode: "service:transmission-openvpn"
   environment:
     - PUID=998
     - PGID=100
     - TZ=Europe/Brussels
   volumes:
     - /Data/Config/Bazarr/:/config
     - /Data/AtomData/Multimedia/Videos/Speelfilms:/movies
     - /Data/AtomData/Multimedia/Videos/TV-series:/tv
   restart: unless-stopped
```

## Docker logs

**Given Stacktrace:**
```Traceback (most recent call last):

  File "/app/bazarr/bin/bazarr/../libs/peewee.py", line 6884, in get

    return clone.execute(database)[0]

  File "/app/bazarr/bin/bazarr/../libs/peewee.py", line 4275, in __getitem__

    return self.row_cache[item]

IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/app/bazarr/bin/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job

    retval = job.func(*job.args, **job.kwargs)

  File "/app/bazarr/bin/bazarr/get_episodes.py", line 88, in sync_episodes

    episodes_to_add.append(episodeParser(episode))

  File "/app/bazarr/bin/bazarr/get_episodes.py", line 295, in episodeParser

    audio_language = TableShows.get(TableShows == episode[\'seriesId\']).audio_language

  File "/app/bazarr/bin/bazarr/../libs/peewee.py", line 6438, in get

    return sq.get()

  File "/app/bazarr/bin/bazarr/../libs/peewee.py", line 6887, in get

    raise self.model.DoesNotExist(\'%s instance matching query does \'

database.TableShowsDoesNotExist: <Model: TableShows> instance matching query does not exist:

SQL: SELECT "t1"."tvdbId", "t1"."alternateTitles", "t1"."audio_language", "t1"."fanart", "t1"."imdbId", "t1"."overview", "t1"."path", "t1"."poster", "t1"."profileId", "t1"."seriesType", "t1"."sonarrSeriesId", "t1"."sortTitle", "t1"."tags", "t1"."title", "t1"."year" FROM "table_shows" AS "t1" WHERE ("t1"."tvdbId" = ?) LIMIT ? OFFSET ?

Params: [0, 1, 0]
```

**Full Log:**

[bazarr-1.log](https://github.com/linuxserver/docker-bazarr/files/6944044/bazarr-1.log)

**Comment by Roxedus** [comment]
This sounds like a issue for the bazarr repository, not a container issue.

**Comment by TiboGabriels** [comment]
my bad, i tought it was the same repository, i'll take a look there, thank you!
