### ISSUE TITLE
Request : update all tasks when Bazarr is starting

### ISSUE THREAD

**Issue by SeeDborg** [linuxserver/docker-bazarr#76]
Hi, I'm using Bazarr on a device that is not on 24H a day.
So my tv shows are not updating, I would like to know if you could add an option to perform all the updating tasks when Bazarr goes online.
Thanks !

**Comment by j0nnymoe** [comment]
This would be something you'll need to ask the bazarr devs to do, not us.

**Comment by SeeDborg** [comment]
Where can I find their github please?
