### ISSUE TITLE
bazarr giving 'Error: 500 Internal Server Error'

### ISSUE THREAD

**Issue by PeuleP** [linuxserver/docker-bazarr#8]
Having an issue with Bazarr running on my Synology 1813+ (DSM 6.2.1-23824 Update 1) with 4GB RAM running with the latest docker container.

Everytime I manually or automated run a 'download all wanted' for TV shows I get the error from the attached file.
Once I turn off the link to Sonarr and only use Radarr it works perfectly, as soon as I turn on Sonarr again I get attached error.
API to Sonarr is set, tested and working, also all shows and episodes are shown correcty.
Also when I try to manually search for 1 individual TV show with multiple missing subs I get the error, when I search for individual subs for individual episodes it works.

Thanks for your support!

![sonarr error](https://user-images.githubusercontent.com/45354800/49008327-db6ec880-f16d-11e8-94aa-8537447a9feb.jpg)

**Comment by PeuleP** [comment]
If it helps to narrow the issue down, I have 95 shows in Sonarr, 5805 episodes of which 345 are missing subtitles

**Comment by aptalca** [comment]
This should probably be reported to bazarr as it seems to be an app related issue rather than docker

**Comment by PeuleP** [comment]
I forgot to report back, but did some more testing by searching for subtitles one series at a time, and everytime when I got to the serie 'Bones' it crashed.
Now I removed Bones from the monotored list and all is well, perhaps there is some weird filename or something for one of the episodes?

**Comment by CHBMB** [comment]
Going to close this now.  @PeuleP Might be helpful to report it to the Bazarr dev.
