### ISSUE TITLE
Installed Python version does not match needed version

### ISSUE THREAD

**Issue by Getn67** [linuxserver/docker-bazarr#85]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Bazarr should start after loading needed resources

## Current Behavior

Bazarr fails, exits, and attempts to restart.

## Steps to Reproduce

1. Fresh install of 'Latest' version of docker
2. Check logs
3.
4.

## Environment
**OS:** Unraid 6.10 rc2
**CPU architecture:** x86_64
**How docker service was installed:** Community Apps Store

Downgrade template to use the requested version of Python or update Bazarr to use the current 3.9.5 version
## Command used to create docker container (run/create/compose/screenshot)

![image](https://user-images.githubusercontent.com/51862012/147377390-f69e722a-4008-4114-8d95-1a458b8ed4ed.png)
![image](https://user-images.githubusercontent.com/51862012/147377406-5e1ff590-bf65-4f18-aad2-859a6cf358ca.png)

## Docker logs

https://pastebin.com/Mm9GG5Qm
https://pastebin.com/P4FvuRtS

**Comment by drizuid** [comment]
https://github.com/linuxserver/docker-bazarr/issues/82

**Comment by thelamer** [comment]
This was resolved upstream.
