### ISSUE TITLE
Remember login when using 'form' auth

### ISSUE THREAD

**Issue by jansengorilla** [linuxserver/docker-bazarr#91]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

Not having to enter my credentials every time i use the web page
## Current Behavior

Form login screen every time, with no option to remember details (like possible with similar method in radarr)
## Alternatives Considered

'Basic' popup screen not nice to use in apple portable environment (iOS/iPadOS)

**Comment by j0nnymoe** [comment]
Not a container related issue. You need to report this to the bazarr Devs.
