### ISSUE TITLE
file path issue. 

### ISSUE THREAD

**Issue by lrdfrd** [linuxserver/docker-bazarr#96]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

see the media files
## Current Behavior

doesnt see the media files
## Steps to Reproduce

1. sync sonarr (binhex)
2. sync radarr (binhex)
3. import lists
4. notice that no matter what you set your path to, bazarr doesnt work.

all containers have their path set to /mnt/user/Storage/Media/
all work except bazarr  (6 other containers follow this bath perfectly)

for example, all tv shows are in /mnt/user/Storage/Media/TV Shows

error for all files tv/movies is: 
BAZARR Error (Path does not exist) trying to get video information for this file: /media/TV Shows/name of show folder / name of show.mkv

i see an extra "media" and its not the correct one as linux is case sensitive.
 shouldnt it think to be looking in /TV Shows/name of show folder / name of show.mkv

## Environment
**OS: unRAID** 
**CPU architecture:** **x86_64**/arm32/arm64
**How docker service was installed:** 

community applications

**Comment by Roxedus** [comment]
Need more context

**Comment by lrdfrd** [comment]
its a pathing issue, im a rookie and didnt realize i needed to add a /media path to the container, figured it our after hopping on discord.  bazarr its self still having issues though  
`<html>
<body>


Exception when servicing <waitress.channel.HTTPChannel connected ***.***.***.***:51179 at 0x14a83e028550> | 06/09/2022 19:51:20 |  
-- | -- | --
  | BAZARR SignalR client for Sonarr is connected and waiting for events. | 06/09/2022 19:45:51 |  
  | BAZARR SignalR client for Radarr is connected and waiting for events. | 06/09/2022 19:45:50 |  
  | BAZARR is started and waiting for request on http://***.***.***.***:6767 | 06/09/2022 19:45:50 |  
  | BAZARR trying to connect to Radarr SignalR feed... | 06/09/2022 19:45:50 |  
  | BAZARR trying to connect to Sonarr SignalR feed... | 06/09/2022 19:45:50 |  
  | Job "Search for wanted Movies Subtitles (trigger: interval[3:00:00], next run at: 2022-09-06 22:42:09 CDT)" raised an exception | 06/09/2022 19:42:25 |  
  | BAZARR Running cache maintenance | 06/09/2022 18:33:34 |  
  | Job "Search for wanted Series Subtitles (trigger: interval[3:00:00], next run at: 2022-09-06 19:58:40 CDT)" raised an exception | 06/09/2022 16:58:47 |  
  | Job "Search for wanted Movies Subtitles (trigger: interval[3:00:00], next run at: 2022-09-06 19:42:09 CDT)" raised an exception | 06/09/2022 16:42:27 |  
  | Job "Search for wanted Series Subtitles (trigger: interval[3:00:00], next run at: 2022-09-06 16:58:40 CDT)" raised an exception | 06/09/2022 13:58:49 |  
  | Job "Search for wanted Movies Subtitles (trigger: interval[3:00:00], next run at: 2022-09-06 16:42:09 CDT)" raised an exception | 06/09/2022 13:42:26 |  
  | Job "Search for wanted Series Subtitles (trigger: interval[3:00:00], next run at: 2022-09-06 13:58:40 CDT)" raised an exception | 06/09/2022 10:59:04 |  
  | HTTPSConnectionPool(host='www.podnapisi.net', port=443): Read timed out. (read timeout=10), retrying in 5 seconds... | 06/09/2022 10:58:56 |  
  | Job "Search for wanted Movies Subtitles (trigger: interval[3:00:00], next run at: 2022-09-06 13:42:09 CDT)" raised an exception | 06/09/2022 10:42:27 |  
  | BAZARR Finished searching for Subtitles to upgrade. Check History for more information. | 06/09/2022 09:35:34 |  
  | Job "Search for wanted Series Subtitles (trigger: interval[3:00:00], next run at: 2022-09-06 10:58:40 CDT)" raised an exception | 06/09/2022 07:58:49 |  
  | Job "Search for wanted Movies Subtitles (trigger: interval[3:00:00], next run at: 2022-09-06 10:42:09 CDT)" raised an exception | 06/09/2022 07:42:42 |  
  | BAZARR All existing movie subtitles indexed from disk. | 06/09/2022 05:00:01 |  
  | Job "Search for wanted Series Subtitles (trigger: interval[3:00:00], next run at: 2022-09-06 07:58:40 CDT)" raised an exception | 06/09/2022 04:59:04 |  
  | HTTPSConnectionPool(host='www.podnapisi.net', port=443): Read timed out. (read timeout=10), retrying in 5 seconds... | 06/09/2022 04:58:56 |  
  | Job "Search for wanted Movies Subtitles (trigger: interval[3:00:00], next run at: 2022-09-06 07:42:09 CDT)" raised an exception | 06/09/2022 04:42:42 |  
  | HTTPSConnectionPool(host='www.podnapisi.net', port=443): Read timed out. (read timeout=10), retrying in 5 seconds... | 06/09/2022 04:42:24 |  
  | BAZARR All existing episode subtitles indexed from disk. | 06/09/2022 04:01:45 |  
  | Job "Search for wanted Series Subtitles (trigger: interval[3:00:00], next run at: 2022-09-06 04:58:40 CDT)" raised an exception | 06/09/2022 01:59:11 |  
  | HTTPSConnectionPool(host='www.podnapisi.net', port=443): Read timed out. (read timeout=10), retrying in 5 seconds... | 06/09/2022 01:59:01 |  
  | Job "Search for wanted Movies Subtitles (trigger: interval[3:00:00], next run at: 2022-09-06 04:42:09 CDT)" raised an exception


</body>
</html>`


and this is in there too.

`Traceback (most recent call last):
  File "/app/bin/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/bin/bazarr/subtitles/wanted/movies.py", line 128, in wanted_search_missing_subtitles_movies
    wanted_download_subtitles_movie(movie[\'radarrId\'])
  File "/app/bin/bazarr/subtitles/wanted/movies.py", line 101, in wanted_download_subtitles_movie
    _wanted_movie(movie)
  File "/app/bin/bazarr/subtitles/wanted/movies.py", line 58, in _wanted_movie
    for result in generate_subtitles(path_mappings.path_replace_movie(movie[\'path\']),
  File "/app/bin/bazarr/subtitles/download.py", line 100, in generate_subtitles
    processed_subtitle = process_subtitle(subtitle=subtitle, media_type=media_type,
  File "/app/bin/bazarr/subtitles/processing.py", line 77, in process_subtitle
    sync_subtitles(video_path=path, srt_path=downloaded_path,
  File "/app/bin/bazarr/subtitles/sync.py", line 29, in sync_subtitles
    subsync.sync(video_path=video_path, srt_path=srt_path, srt_lang=srt_lang, media_type=media_type,
  File "/app/bin/bazarr/subtitles/tools/subsyncer.py", line 64, in sync
    self.args = parser.parse_args(args=unparsed_args)
  File "/app/bin/bazarr/../libs/argparse.py", line 1728, in parse_args
    self.error(msg % \' \'.join(argv))
  File "/app/bin/bazarr/../libs/argparse.py", line 2392, in error
    self.exit(2, _(\'%s: error: %s\
\') % (self.prog, message))
  File "/app/bin/bazarr/../libs/argparse.py", line 2380, in exit
    _sys.exit(status)
SystemExit: 2`

but im going direct to bazarr for that. ty
