### ISSUE TITLE
Language profile per season

### ISSUE THREAD

**Issue by jansengorilla** [linuxserver/docker-bazarr#99]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

Ability to specify language profile per series season, or even episode.
## Current Behavior

Only one profile available for entire series. For older series with missing subs, this will keep repeating the search. For example, i have a profile to prefer dutch, otherwise english. When older episodes are unavailable, i would like to specify another profile (only english or even none) per episode or season.

**Comment by Roxedus** [comment]
This is not the correct repository for this
